repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-toml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
        types: [python]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [
          --ignore=E203, E266, E501, W503, F403, F401,
          --max-line-length=89,
          --max-complexity=18,
          --select=B,C,E,F,W,T4,B9
        ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest ./test/ -v
        language: python
        types:
          - python
        pass_filenames: false