repos:
  - repo: https://github.com/afergadis/irrCAC
    rev: master
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
      - id: commitizen
        stages: [commit-msg]
